name: Create release

on:
  push:
    branches:
      - released
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1

      - name: Pick version name
        id: app-version
        run: |
          echo "$(ruby scripts/pick-version-name.rb)" > TMP_LOG
          echo "version-name=$(cat TMP_LOG)" >> "$GITHUB_OUTPUT"

      - name: Set git tag
        run: |
          echo "${{ steps.app-version.outputs.version-name }}" > TAG_NAME
          git tag "$(cat TAG_NAME)"
          git push origin "$(cat TAG_NAME)"

      - name: Create release
        run: gh release create "${{ steps.app-version.outputs.version-name }}" --generate-notes --title "${{ steps.app-version.outputs.version-name }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
